version: '3.3'
services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ../templates/react/build/static:/app/static
      - ../templates/react/build/assets:/app/assets
    ports:
      - "9090:9090"
  nginx:
    container_name: ngnix_proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./main.conf:/etc/nginx/nginx.conf
      - ../templates/react/build/static:/app/static
      - ../templates/react/build/assets:/app/assets
      - ./mnt/server.crt:/mnt/server.crt
      - ./mnt/server.key:/mnt/server.key

    depends_on:
      - web
